---
- name: BBuddy Server
  hosts: all
  any_errors_fatal: true
  roles:
    - jdk8
    - gradle
    - role: mysql
      mysql:
        database: bbuddy
        user: nerd
        password: dbs3cr3t
    - xserver
