spring:
    datasource:
        password: dbs3cr3t
        testWhileIdle: true
        username: nerd
        validationQuery: SELECT 1
    jpa:
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
        show-sql: true
    messages:
        basename: BindingErrorMessages

application:
    perPageLimit: 10

---

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/bbuddydev?createDatabaseIfNotExist=true&useSSL=false

server:
  port: 8090

---

spring:
  profiles: test
  datasource:
    url: jdbc:mysql://localhost:3306/bbuddytest?createDatabaseIfNotExist=true&useSSL=false
  jpa:
    hibernate:
      ddl-auto: create

server:
  port: 8080
